### PyTorch 구조 이해

In [1]:
import torch
import torch.nn as nn
from torchinfo import summary
import torchviz

In [2]:
class Net(nn.Module):
    # 모델 구성 요소 생성 및 구조 설정
    def __init__(self):
        super(Net, self).__init__()
        
        self.fc1 = nn.Linear(8, 4)
        self.fc2 = nn.Linear(4, 2)
        self.fc3 = nn.Linear(2, 1)
    
    # 순방향 학습 진행 함수
    def forward(self, x):
        return self.fc3(self.fc2(self.fc1(x)))

In [3]:
class Net0(nn.Module):
    
    # 모델 구성 요소 생성 및 구조 설정
    def __init__(self):
        super(Net, self).__init__()
        self.input = nn.Linear(8, 4)
        self.layer2 = nn.Linear(4, 2)
        self.drop = nn.Dropout(0.5)
        self.layer3 = nn.Linear(2, 1)
    
    # 순방향 학습 진행 함수
    def forward(self, x):
        return self.layer3(self.drop(self.layer2(self.layer1)))

In [4]:
## 모델 인스턴스 생성
model = Net()
print(model)

Net(
  (fc1): Linear(in_features=8, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=2, bias=True)
  (fc3): Linear(in_features=2, out_features=1, bias=True)
)


In [5]:
# fc1 : (w 8개 + b 1개) * 퍼셉트론 4개 = 총 36개 (Param)
# fc2 : (w 4개 + b 1개) * 퍼셉트론 2개 = 총 10개 (Param)
# fc3 : (w 2개 + b 1개) * 퍼셉트론 1개 = 총  3개 (Param)
summary(model)

Layer (type:depth-idx)                   Param #
Net                                      --
├─Linear: 1-1                            36
├─Linear: 1-2                            10
├─Linear: 1-3                            3
Total params: 49
Trainable params: 49
Non-trainable params: 0

In [6]:
## 모델 인스턴스 속성 확인
model.fc1

Linear(in_features=8, out_features=4, bias=True)

In [7]:
# 모델의 특정 층 추출
model.fc1.weight, model.fc1.bias

(Parameter containing:
 tensor([[ 0.0725,  0.0345, -0.1504, -0.0948,  0.3082,  0.0909, -0.1499,  0.2968],
         [-0.1212, -0.2438, -0.1029, -0.1722,  0.2776,  0.2017, -0.0101, -0.0403],
         [-0.1016,  0.1990, -0.1417,  0.1526, -0.0723, -0.0384, -0.0529, -0.2112],
         [ 0.2284, -0.1267, -0.2498,  0.1079,  0.0661, -0.2850, -0.2631,  0.0896]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.3043,  0.2552,  0.1666,  0.2757], requires_grad=True))

In [8]:
## 모델의 각 층별 w, b 텐서 정보 확인
for param in model.parameters():
    print(param, end='\n\n')

Parameter containing:
tensor([[ 0.0725,  0.0345, -0.1504, -0.0948,  0.3082,  0.0909, -0.1499,  0.2968],
        [-0.1212, -0.2438, -0.1029, -0.1722,  0.2776,  0.2017, -0.0101, -0.0403],
        [-0.1016,  0.1990, -0.1417,  0.1526, -0.0723, -0.0384, -0.0529, -0.2112],
        [ 0.2284, -0.1267, -0.2498,  0.1079,  0.0661, -0.2850, -0.2631,  0.0896]],
       requires_grad=True)

Parameter containing:
tensor([-0.3043,  0.2552,  0.1666,  0.2757], requires_grad=True)

Parameter containing:
tensor([[ 0.2968,  0.3994,  0.2944,  0.4338],
        [-0.3626, -0.4439, -0.2297,  0.3417]], requires_grad=True)

Parameter containing:
tensor([ 0.3591, -0.2723], requires_grad=True)

Parameter containing:
tensor([[-0.3381,  0.1480]], requires_grad=True)

Parameter containing:
tensor([-0.4181], requires_grad=True)


In [9]:
for param in model.named_parameters():
    print(param, end='\n\n')

('fc1.weight', Parameter containing:
tensor([[ 0.0725,  0.0345, -0.1504, -0.0948,  0.3082,  0.0909, -0.1499,  0.2968],
        [-0.1212, -0.2438, -0.1029, -0.1722,  0.2776,  0.2017, -0.0101, -0.0403],
        [-0.1016,  0.1990, -0.1417,  0.1526, -0.0723, -0.0384, -0.0529, -0.2112],
        [ 0.2284, -0.1267, -0.2498,  0.1079,  0.0661, -0.2850, -0.2631,  0.0896]],
       requires_grad=True))

('fc1.bias', Parameter containing:
tensor([-0.3043,  0.2552,  0.1666,  0.2757], requires_grad=True))

('fc2.weight', Parameter containing:
tensor([[ 0.2968,  0.3994,  0.2944,  0.4338],
        [-0.3626, -0.4439, -0.2297,  0.3417]], requires_grad=True))

('fc2.bias', Parameter containing:
tensor([ 0.3591, -0.2723], requires_grad=True))

('fc3.weight', Parameter containing:
tensor([[-0.3381,  0.1480]], requires_grad=True))

('fc3.bias', Parameter containing:
tensor([-0.4181], requires_grad=True))


In [10]:
for child in model.children():
    print(child, end='\n\n')

Linear(in_features=8, out_features=4, bias=True)

Linear(in_features=4, out_features=2, bias=True)

Linear(in_features=2, out_features=1, bias=True)


In [11]:
for child in model.named_children():
    print(child, end='\n\n')

('fc1', Linear(in_features=8, out_features=4, bias=True))

('fc2', Linear(in_features=4, out_features=2, bias=True))

('fc3', Linear(in_features=2, out_features=1, bias=True))


Layer의 가중치 설정

In [12]:
# 세이비어 알고리즘의 가중치 초기화
nn.init.xavier_uniform_(model.fc1.weight)

Parameter containing:
tensor([[-0.5266, -0.0997, -0.4689,  0.0807,  0.5440, -0.2541, -0.3577,  0.0687],
        [-0.6068,  0.2516,  0.3362,  0.4546,  0.0276, -0.5801,  0.0769, -0.6767],
        [ 0.4358,  0.6410, -0.4420,  0.2478, -0.4128, -0.1031, -0.1229, -0.1142],
        [-0.2141,  0.4666, -0.3505,  0.0784,  0.3641,  0.0436, -0.6333,  0.6571]],
       requires_grad=True)

In [13]:
# 헤 알고리즘의 가중치 초기화
nn.init.kaiming_normal_(model.fc2.weight)

Parameter containing:
tensor([[ 0.6828,  0.2317,  0.5290, -0.4147],
        [-0.7864, -0.4126, -0.0165,  0.0962]], requires_grad=True)

In [15]:
import os

dir = '../data/model'
if not os.path.exists(dir):
    os.makedirs(dir)

torch.save(model, '../data/model/exmodel.pt')