예제 출처 : https://www.youtube.com/watch?v=k60oT_8lyFw&t=4978s

In [1]:
import torch

In [3]:
a = torch.randn(3, 3)
print(a)

tensor([[-1.8993, -0.2533, -0.4023],
        [-0.3298,  0.0427,  0.5499],
        [-0.3475, -0.1749, -0.4948]])


In [6]:
type(a.requires_grad)

bool

In [7]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [10]:
b = (a * a).sum()
b

tensor(4.6422, grad_fn=<SumBackward0>)

In [11]:
b.grad_fn   # 어떤 연산이 수행되었는지에 대한 기록

In [15]:
c = a * a 
out = c.mean()
out.grad_fn

계산이 완료된 후, .backward()를 호출하면 자동으로 역전파 계산이 가능하고, .grad 속성에 누적됨

In [18]:
x = torch.ones(3, 3, requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [19]:
y = x + 5
print(y)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)


In [20]:
z = y * y
out = z.mean()
print(z, out)

tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]], grad_fn=<MulBackward0>) tensor(36., grad_fn=<MeanBackward0>)


In [21]:
out.backward()

In [22]:
print(x)
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333]])


In [24]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([1311.9291,  709.6655, -976.4540], grad_fn=<MulBackward0>)


with torch.no_grad(): 를 사용하여 기울기의 없데이트를 하지 않음

토치비전(torchvision)은 파이토치에서 제공하는 데이터셋들이 모여있는 패키지
- transforms : 전처리할 때 사용하는 모듈
- DataLoader의 인자로 들어갈 transform을 미리 정의할 수 있고, Compose를 통해 리스트 안에 있는 함수 순서대로 전처리 진행
- ToTensor()를 하는 이유는 torchvision이 PIL Image 형태로만 입력을 받기 때문에 데이터 처리를 위해서 Tensor형으로 변환 필요

In [28]:
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
from torchvision import datasets

mnist_transform = transforms.Compose([transforms.ToTensor(),
                                      transforms.Normalize(mean=(0.5), std=(1.0))])

In [27]:
trainset = datasets.MNIST(root='/content/',
                          train=True, download=True,
                          transform=mnist_transform)
testset = datasets.MNIST(root='/content/',
                          train=False, download=True,
                          transform=mnist_transform)

100.0%


Extracting /content/MNIST\raw\train-images-idx3-ubyte.gz to /content/MNIST\raw



100.0%


Extracting /content/MNIST\raw\train-labels-idx1-ubyte.gz to /content/MNIST\raw



100.0%


Extracting /content/MNIST\raw\t10k-images-idx3-ubyte.gz to /content/MNIST\raw



100.0%

Extracting /content/MNIST\raw\t10k-labels-idx1-ubyte.gz to /content/MNIST\raw


DataLoader는 데이터 전체를 보관했다가 실제 모델 학습을 할 때 batch_size 크기만큼 데이터를 가져온다.

In [29]:
train_loader = DataLoader(trainset, batch_size=8, shuffle=True, num_workers=2)
test_loader = DataLoader(testset, batch_size=8, shuffle=False, num_workers=2)

In [36]:
len(trainset)

60000

torch.nn 패키지 (neural network)
주로 가중치(w), 편향(b) 값들이 내부에서 자동으로 생성되는 레이어들을 사용할 때 사용 (weight 값들을 직접 선언 안 함)

In [37]:
import torch.nn as nn

In [39]:
input = torch.randn(128, 20)
print(input)

m = nn.Linear(20, 30)   # 신경망 계층 (in_features=20, out_features=30)
print(m)

output = m(input)
print(output)
print(output.size())

tensor([[ 0.3653,  1.7625,  0.6208,  ...,  0.6120,  0.9919, -2.0986],
        [-2.4313, -0.1517, -0.6972,  ..., -1.4941,  0.3822,  0.2904],
        [-0.4385,  1.4965,  1.5754,  ..., -0.4667, -0.5185, -0.0683],
        ...,
        [ 1.5275, -0.5521,  0.9346,  ..., -0.7999, -0.8114,  0.5746],
        [ 0.3743,  0.9224, -0.4289,  ...,  0.8920,  0.8279,  0.2976],
        [ 1.3614, -0.3739, -0.4832,  ...,  0.2890, -0.4224,  0.5154]])
Linear(in_features=20, out_features=30, bias=True)
tensor([[-0.0618, -1.3501,  0.5973,  ..., -0.6753, -1.0404, -0.7834],
        [ 0.4703, -0.2507, -0.3069,  ...,  0.3727,  0.2439,  0.2289],
        [-0.5002, -1.3293, -0.6277,  ..., -1.0429, -0.0305,  0.5356],
        ...,
        [-0.7719, -0.2500, -0.3151,  ..., -0.2878, -0.0811,  1.2625],
        [-0.4426,  0.4490, -0.6307,  ..., -0.1663,  0.9452, -0.0543],
        [-0.1079, -0.4953,  0.8592,  ..., -0.9361, -0.5353,  0.6475]],
       grad_fn=<AddmmBackward0>)
torch.Size([128, 30])


In [40]:
input = torch.randn(20, 16, 50, 100)
print(input.size())

torch.Size([20, 16, 50, 100])


In [42]:
m = nn.Conv2d(16, 33, 3, stride=2)
m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2))
print(m)

Conv2d(16, 33, kernel_size=(3, 5), stride=(2, 1), padding=(4, 2))


In [45]:
ouput = m(input)
print(output.size())

torch.Size([128, 30])
