### 텐서 연결 & 결합

In [1]:
import torch

In [16]:
# 텐서 데이터 생성
torch.manual_seed(12)

# 임의의 [0, 1) 실수
x = torch.rand(2, 10)

# 임의의 정수 : [low, high)
y = torch.randint(0, 2, (10,))
y2 = torch.randint(0, 2, (2, 10))

In [17]:
print(f'x => {x.shape}, {x.ndim}D')
print(f'y => {y.shape}, {y.ndim}D')
print(f'y2 => {y2.shape}, {y2.ndim}D')

x => torch.Size([2, 10]), 2D
y => torch.Size([10]), 1D
y2 => torch.Size([2, 10]), 2D


In [29]:
# tensor 연결 cat([텐서1, 텐서2, ...])
# xy1 = torch.cat([x, y], dim=1) ------> RuntimeError: Tensors must have same number of dimensions: got 2 and 1
xy1 = torch.cat([x, y2], dim=0)     # dim=0 => 아래쪽으로 붙임 (행이 늘어남)
print(xy1.shape)
print(xy1)

torch.Size([4, 10])
tensor([[0.4657, 0.2328, 0.4527, 0.5871, 0.4086, 0.1272, 0.6373, 0.2421, 0.7312,
         0.7224],
        [0.1992, 0.6948, 0.5830, 0.6318, 0.5559, 0.1262, 0.9790, 0.8443, 0.1256,
         0.4456],
        [1.0000, 1.0000, 0.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])


In [ ]:
xy2 = torch.cat([x, y2], dim=1)     # dim=1 => 오른쪽으로 붙임 (피처가 늘어남)
print(xy2.shape)
print(xy2)

In [35]:
# 열 단위로 최대값 및 최대값의 인덱스(몇 번째 행) 저장
# 열 단위 => 한 열 안에서
max_value = xy1.max(dim=0)[0]
max_index = xy1.max(dim=0)[1]

max_value, max_index

(tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.9790, 0.8443, 0.7312,
         0.7224]),
 tensor([2, 2, 3, 2, 2, 3, 1, 1, 0, 0]))

In [36]:
# 행 단위로 최대값 및 최대값의 인덱스(몇 번째 열) 저장
# 행 단위 => 한 행 안에서
max_value = xy1.max(dim=1)[0]
max_index = xy1.max(dim=1)[1]

max_value, max_index

(tensor([0.7312, 0.9790, 1.0000, 1.0000]), tensor([8, 6, 0, 2]))

In [45]:
import pandas as pd

data = pd.DataFrame({'A':[10, 20], 'B':[20, 22], 'C': [30, 33]})
data

A   B   C
0  10  20  30
1  20  22  33

In [46]:
data.max(), data.max(axis=0)

(A    20
 B    22
 C    33
 dtype: int64,
 A    20
 B    22
 C    33
 dtype: int64)

In [47]:
data.max(axis=1)

0    30
1    33
dtype: int64

### Tensor 차원 형태 변경

In [50]:
t1 = torch.tensor([[[1, 2], [11, 22], [44, 55]]])
print(f't1 => {t1.shape}, {t1.ndim}D')

t1 => torch.Size([1, 3, 2]), 3D


In [55]:
# 2개의 차원을 변경하는 메서드
t11 = t1.transpose(0, 2)    # 0번째 차원과 2번째 차원을 맞바꿀래
print(f't11 => {t11.shape}, {t11.ndim}D')

t11 => torch.Size([2, 3, 1]), 3D


In [56]:
# 모든 차원을 변경하는 메서드
t22 = t1.permute(1, 2, 0)
print(f't22 => {t22.shape}, {t22.ndim}D')

t22 => torch.Size([3, 2, 1]), 3D


In [57]:
# 메타데이터 정보만 바뀌고, 실제 데이터가 저장된 메모리의 주소는 변경 X
print(f'{t1.data_ptr()}, {t11.data_ptr()}, {t22.data_ptr()}')

6266517129344, 6266517129344, 6266517129344
