### 텐서(Tensor) 살펴보기
- PyTorch에서 데이터 저장 자료형
- 모델 입력(input), 출력(output) 데이터 형태

(1) 모듈 로딩

In [1]:
import torch

* Tensor 속성 관련 함수

In [2]:
torch.__version__

'2.2.0'

In [3]:
# 매개변수 : 텐서 인스턴스, 텐서 변수명
def printTensor(tensor, name):
    print(f'[Tensor {name}\'s Attribute]')
    print(f'- tensor.shape : {tensor.shape}')
    print(f'- tensor.ndim : {tensor.ndim}D')
    print(f'- tensor.dtype : {tensor.dtype}')
    print(f'- tensor.device : {tensor.device}')
    print(f'- tensor.requires_grad : {tensor.requires_grad}')
    print(f'- tensor.data \n{tensor.data}')

- Tensor 생성 (1) 특정 데이터 타입의 텐서 생성
    - 타입별 텐서 클래스 생성자 활용
    - 예) IntTensor(), FloatTensor(), BoolTensor()

In [4]:
# 정수 타입 텐서 생성
t1 = torch.IntTensor(10)                # 1차원 (길이 10) 생성
t2 = torch.IntTensor([10, 20])          # 1차원 (길이  2) 생성
t3 = torch.BoolTensor([1, 2, 0, -1])    # 1차원 (길이  4) 생성
t4 = torch.FloatTensor([10, 20])        # 1차원 (길이  2) 생성

In [5]:
printTensor(t1, 't1')

[Tensor t1's Attribute]
- tensor.shape : torch.Size([10])
- tensor.ndim : 1D
- tensor.dtype : torch.int32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([-905965200,       1532,          0,          0,          0,          0,
                 0,          0,          0,          0], dtype=torch.int32)


In [6]:
printTensor(t2, 't2')

[Tensor t2's Attribute]
- tensor.shape : torch.Size([2])
- tensor.ndim : 1D
- tensor.dtype : torch.int32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([10, 20], dtype=torch.int32)


In [7]:
printTensor(t3, 't3')

[Tensor t3's Attribute]
- tensor.shape : torch.Size([4])
- tensor.ndim : 1D
- tensor.dtype : torch.bool
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([ True,  True, False,  True])


In [8]:
printTensor(t4, 't4')

[Tensor t4's Attribute]
- tensor.shape : torch.Size([2])
- tensor.ndim : 1D
- tensor.dtype : torch.float32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([10., 20.])


- Tensor 생성 (2) 원하는 값으로 텐서 생성 => torch.tensor()

In [9]:
t1 = torch.tensor(10)       # scalar 데이터, int64
printTensor(t1, 't1')

[Tensor t1's Attribute]
- tensor.shape : torch.Size([])
- tensor.ndim : 0D
- tensor.dtype : torch.int64
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
10


In [10]:
t1 = torch.tensor(10.)  # scalar 데이터, float32
printTensor(t1, 't1')

[Tensor t1's Attribute]
- tensor.shape : torch.Size([])
- tensor.ndim : 0D
- tensor.dtype : torch.float32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
10.0


In [11]:
t1 = torch.tensor(10., dtype=torch.int32)   # scalar 데이터, int32
printTensor(t1, 't1')

[Tensor t1's Attribute]
- tensor.shape : torch.Size([])
- tensor.ndim : 0D
- tensor.dtype : torch.int32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
10


C:\Users\kdp\AppData\Local\Temp\ipykernel_30148\411252444.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  t1 = torch.tensor(10., dtype=torch.int32)   # scalar 데이터, int32


In [12]:
t1 = torch.tensor(10., dtype=torch.bool)    # scalar 데이터, bool
printTensor(t1, 't1')

[Tensor t1's Attribute]
- tensor.shape : torch.Size([])
- tensor.ndim : 0D
- tensor.dtype : torch.bool
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
True


In [13]:
t1 = torch.tensor([1, 2, 3], dtype=torch.int8)  # 1D 데이터
printTensor(t1, 't1')

[Tensor t1's Attribute]
- tensor.shape : torch.Size([3])
- tensor.ndim : 1D
- tensor.dtype : torch.int8
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([1, 2, 3], dtype=torch.int8)


- Tensor 생성 (3) 특정 값으로 채운 텐서 => 0, 1 등의 값

In [14]:
# 0으로 채운 텐서
t1 = torch.zeros(5, dtype=torch.int8)       # 1D 데이터
printTensor(t1, 't1')

[Tensor t1's Attribute]
- tensor.shape : torch.Size([5])
- tensor.ndim : 1D
- tensor.dtype : torch.int8
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([0, 0, 0, 0, 0], dtype=torch.int8)


In [15]:
# 0으로 채운 텐서
t1 = torch.zeros((5, 5), dtype=torch.int8)  # 2D 데이터
printTensor(t1, 't1')

[Tensor t1's Attribute]
- tensor.shape : torch.Size([5, 5])
- tensor.ndim : 2D
- tensor.dtype : torch.int8
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int8)


In [16]:
# 1으로 채운 텐서
t1 = torch.ones((5, 5), dtype=torch.int8)   # 2D 데이터
printTensor(t1, 't1')

[Tensor t1's Attribute]
- tensor.shape : torch.Size([5, 5])
- tensor.ndim : 2D
- tensor.dtype : torch.int8
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data 
tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int8)


In [17]:
# 이미 존재하는 텐서와 동일한 shape으로 잡고 값 채우기 => zeros_like(), ones_like()
imgT = torch.tensor([[2, 3, 4, 5, 6, 7], [2, 3, 4, 5, 6, 7]])
print(imgT.shape)

torch.Size([2, 6])


In [18]:
zero_img = torch.zeros_like(imgT)
print(zero_img)

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])


In [19]:
one_img = torch.ones_like(imgT)
print(one_img)

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])


In [20]:
full_img = torch.full_like(imgT, 2)
print(full_img)

tensor([[2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2]])


In [21]:
# 대각선 방향으로 1 채우기 => eye()
t1 = torch.eye(3)
print(t1)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


- Tensor 생성 (4) 랜덤하게 값 생성

In [22]:
torch.manual_seed(12)   # 랜덤 초기값 생성
t5 = torch.rand(2, 3)   # [0, 1) 범위 안에서 랜덤 생성
t6 = torch.randn(2, 3)  # standard normal 분포에서 랜덤 생성
t7 = torch.randint(low=1, high=10, size=(2,3))  # [low, high)

In [23]:
print(t5)
print(t6)
print(t7)

tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])
tensor([[ 1.5869,  1.1268, -1.2274],
        [-0.8216, -1.7861,  0.6167]])
tensor([[8, 4, 6],
        [2, 2, 2]])


- Tensor 생성 (5) ndarray 객체로 생성

In [24]:
# 데이터 생성
import numpy as np

data = np.array([11, 22, 33])
print(data, type(data))

[11 22 33] <class 'numpy.ndarray'>


In [25]:
t1 = torch.from_numpy(data)
print(t1)

tensor([11, 22, 33], dtype=torch.int32)


In [26]:
t2 = torch.as_tensor(data)
print(t2)

tensor([11, 22, 33], dtype=torch.int32)


In [27]:
t3 = torch.tensor(data)
print(t3)

tensor([11, 22, 33], dtype=torch.int32)


In [28]:
# ndarray 원소 변경
data[0] = 100

In [29]:
# from_numpy(), as_tensor() => 데이터 공유
# tensor()                  => 복사본 생성
print(data, t1, t2, t3, sep='\n')

[100  22  33]
tensor([100,  22,  33], dtype=torch.int32)
tensor([100,  22,  33], dtype=torch.int32)
tensor([11, 22, 33], dtype=torch.int32)
