#### [ 미니 테스트  2024-03-13 ]<hr>

1. 화면상에서 PyTorch에서 데이터를 저장하는 단위는 (텐서)입니다.
2. 1번문제에 해당하는 것의 특징을 간략히 설명해 보세요.  
    - 대부분 메모리에서 인접하게(contiguously) 할당되어 있어, 데이터의 접근속도, 연산속도가 빠른 것이 특징이나, stride가 일정하지 않은 상황이 발생하여 메모리가 인접하게 할당되지 않는 경우도 존재한다.
3. PyTorch에서 정수형 데이터를 저장하는 데이터 타입을 모두 나열하세요. 간단한 데이터 타입의 크기 설명도 함께 작성하세요.
    - int8, int16, int32, int64, uint8
    - int8, int16, int32는 각각 8비트, 16비트, 32비트를 사용하여 정수를 나타내는 타입이며, 음수/0/양수 표현이 가능하다.
    - uint8, uint16, uint32는 각각 8비트, 16비트, 32비트를 사용하여 정수를 나타내나, 음수 범위는 표현하지 않는다. 그래서 0/양수 표현만 가능하고, 음수를 사용하지 않는만큼 양수를 더 표현할 수 있는 것이 특징이다.
    - uint8 = Byte, int16 = short, int64 = long

In [1]:
import torch

4. PyTorch에 논리형 데이터로 저장 후 속성을 출력하는 코드를 작성하세요.
    - 데이터 : 10, -5, 1.4, 7, 0, -1, 0

In [23]:
q4 = torch.tensor([10, -5, 1.4, 7, 0, -1, 0], dtype=torch.bool)
q4.shape, q4.ndim, q4.dtype, q4.is_contiguous()

(torch.Size([7]), 1, torch.bool, True)

5. 10개의 0 데이터를 2차원으로 저장 코드를 작성하세요.

In [3]:
# q5 = torch.tensor([0]*10).reshape(-1, 5)
q5 = torch.zeros((2, 5), dtype=torch.int8)
q5

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int8)

6. 5개의 1 데이터가 대각선으로 저장되는 2차원 저장 코드를 작성하세요.

In [4]:
q6 = torch.eye(5)
q6

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

7. 5번에서 저장된 형태와 동일하지만 값이 3이 저장된 코드를 작성하세요.

In [5]:
q7 = torch.full_like(q5, 3)
q7

tensor([[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]], dtype=torch.int8)

8. ndarray 데이터를 PyTorch에 저장하는 코드를 작성하세요.

In [6]:
import numpy as np

arr = np.arange(7, 101, 7)
torch.tensor(arr, dtype=torch.float32)

tensor([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70., 77., 84., 91., 98.])

9. 아래 조건에 맞는 데이터를 PyTorch에 저장하는 코드를 작성하세요.
    - 이미지 파일 : flower.jpg
    - 이미지 크기 : 120x80
    - 데이터 타입 : uint8
    - 데이터 : 임의의 값

In [24]:
filename = 'flower.jpg'

# 120x80 : 120 ~ 가로, 80 ~ 세로
torch.randint(0, 255, (80, 120), dtype=torch.uint8).shape    # (80 ~ 행/세로, 120 ~ 열/가로)

torch.Size([80, 120])

10. 아래 조건에 맞도록 코드를 작성하세요.
    (1) 1D으로 저장
    (2) (1)에서 저장된 데이터를 요소 수 변경 없이 3D로 변환
    (3) (2)에서 저장된 데이터의 2개 차원 변경한 3D로 변환
    (4) (2)에서 저장된 데이터의 3개 차원 모두 변경한 3D로 변환

In [8]:
q10 = torch.randint(0, 255, (10,))

q101 = q10.unsqueeze(dim=-1).unsqueeze(-1)

q102 = q101.transpose(0, 2)

q103 = q101.permute(2, 0, 1)

print(q10.shape, q101.shape, q102.shape, q103.shape)

torch.Size([10]) torch.Size([10, 1, 1]) torch.Size([1, 1, 10]) torch.Size([1, 10, 1])


11. 아래 조건에 맞도록 코드를 작성하세요.
데이터
국어 90, 70, 80
영어 70, 100, 80
수학 99, 88, 77
(1) 위의 데이터를 저장
(2) 과목별 합계, 평균, 최고점수 출력
(3) 한 사람의 국어, 영어, 수학 점수 합계, 평균, 최고점수 출력

In [34]:
q11 = torch.tensor([[90, 70, 80], [70, 100, 80], [99, 88, 77]])
print('과목별')
print(f'합계: {q11.sum(dim=0)}, 평균: {q11.float().mean(dim=0)}, \n최고점수: {q11.max(dim=0)}')  # 과목별 합계, 평균, 최고점수
print('한 사람별')
print(f'합계: {q11.sum(dim=1)}, 평균: {q11.float().mean(dim=1)}, \n최고점수: {q11.max(dim=1)}')  # 과목별 합계, 평균, 최고점수

과목별
합계: tensor([259, 258, 237]), 평균: tensor([86.3333, 86.0000, 79.0000]), 
최고점수: torch.return_types.max(
values=tensor([ 99, 100,  80]),
indices=tensor([2, 1, 0]))
한 사람별
합계: tensor([240, 250, 264]), 평균: tensor([80.0000, 83.3333, 88.0000]), 
최고점수: torch.return_types.max(
values=tensor([ 90, 100,  99]),
indices=tensor([0, 1, 0]))


12. 아래 조건에 맞도록 코드를 작성하세요.
    - (1) 위에 데이터를 저장
    - (2) 데이터1과 데이터2의 사칙연산 결과
    - (3) 데이터1과 데이터2의 행렬곱셈

In [10]:
q12 = torch.tensor([0.5, 0.2, 0.7])


In [11]:
q11 + q12

tensor([[ 90.5000,  70.2000,  80.7000],
        [ 70.5000, 100.2000,  80.7000],
        [ 99.5000,  88.2000,  77.7000]])

In [12]:
q11 - q12

tensor([[89.5000, 69.8000, 79.3000],
        [69.5000, 99.8000, 79.3000],
        [98.5000, 87.8000, 76.3000]])

In [13]:
q11 * q12

tensor([[45.0000, 14.0000, 56.0000],
        [35.0000, 20.0000, 56.0000],
        [49.5000, 17.6000, 53.9000]])

In [14]:
q11 / q12

tensor([[180.0000, 350.0000, 114.2857],
        [140.0000, 500.0000, 114.2857],
        [198.0000, 440.0000, 110.0000]])

In [19]:
q11.half().matmul(q12.half()) # 둘 다 실수형으로 바꾸면 문제 없음

tensor([115., 111., 121.], dtype=torch.float16)